apiVersion: v1
kind: Service
metadata:
  name:  miniproject-rtp-service
  namespace: miniproject
spec:
  type: NodePort
  selector:
    app: miniproject-rtp
  ports:
  - nodePort: 30082
    port: 80
    targetPort: 80